Plot simulation output for better visualization
ufcg-lsd/autoscaling-analyser pull request #23
Opened 2022-07-03 20:14 UTC by kmmelcher

2022-07-04 20:49 UTC, kmmelcher commented
![image](https://user-images.githubusercontent.com/20446656/177215037-0f881dd7-f61b-48d4-aed1-8f7d2ce5e73f.png)
Como resolver esses conflitos?
eles não afetam o funcionamento do simulador, mas podem dar problema.
Eu tentei usando a notação da package ggplot2::ggplot, para evitar ambiguidade, mas os erros continuam.
Talvez tem que tentar colocar a package em todas as funções importadas.

2022-07-04 20:49 UTC, kmmelcher commented
[simple_scaling_cores.pdf](https://github.com/ufcg-lsd/autoscaling-analyser/files/9041976/simple_scaling_cores.pdf)
[simple_scaling_utilization.pdf](https://github.com/ufcg-lsd/autoscaling-analyser/files/9041977/simple_scaling_utilization.pdf)
[target_tracking_cores.pdf](https://github.com/ufcg-lsd/autoscaling-analyser/files/9041978/target_tracking_cores.pdf)
[target_tracking_utilization.pdf](https://github.com/ufcg-lsd/autoscaling-analyser/files/9041979/target_tracking_utilization.pdf)

2022-07-05 20:37 UTC, kmmelcher commented on src/plot.R
> +  }
Tem alguma sugestão de como evitar essa duplicação de código?
Ou ainda melhor, acha que essas funções de plot específicas de cada políticas deviam estar implementadas nas políticas? @issilva5

2022-07-06 11:38 UTC, issilva5 requested changes

2022-07-06 11:38 UTC, issilva5 commented on config.yaml
> +cores_plot_file: "output/simple_scaling_cores.pdf"
Não sei se essas configurações são muito relevantes. Eu deixaria só `plot: True`.

2022-07-06 11:38 UTC, issilva5 commented on src/plot.R
> +  }
```suggestion

plot <- data %>% ggplot2::ggplot(aes(x = timestamp - min(timestamp), y = SystemUtilization)) +
      geom_line() +
      theme_minimal() +
      labs(y = "CPUtilization (%)", x = "Time (s)")

  if (configs$policies$use == "simple_scaling") {
    upper_bound <- policy_parameters$upper_bound
    lower_bound <-policy_parameters$lower_bound
    
    plot <- plot +
      geom_hline(yintercept = upper_bound, color = "red") +
      geom_text(aes(x = 70, y = upper_bound+2, label = "Upper Bound"), size = 3, color = "red") +
      geom_hline(yintercept = lower_bound, color = "blue") +
      geom_text(aes(x = 70, y = lower_bound-2, label = "Lower Bound"), size = 3, color = "blue")
  
  } else if (configs$policies$use == "target_tracking") {
    target <- policy_parameters$target_value
    
    plot <- plot +
      geom_hline(yintercept = target, color = "red") +
      geom_text(aes(x = 120, y = target+2, label = "Target threshold"), size = 3, color = "red")
  
  }
```

2022-07-06 11:38 UTC, issilva5 commented on src/plot.R
> +  }
Talvez tenha que mudar algo no ggsave, confere.

2022-07-06 11:38 UTC, issilva5 commented on src/plot.R
> +  }
Also, a unidade do plot tá como segundos, mas é minutos.

2022-07-06 14:24 UTC, kmmelcher commented on config.yaml
> +cores_plot_file: "output/simple_scaling_cores.pdf"
Feito

2022-07-06 14:44 UTC, kmmelcher commented on src/plot.R
> +  }
Obrigado! refatorei e alterei a unidade

2022-07-11 17:58 UTC, issilva5 approved these changes

2022-07-11 19:20 UTC, merged