Updating the autoscaling
ufcg-lsd/autoscaling-analyser pull request #7
Opened 2022-03-10 14:20 UTC by issilva5

2022-03-10 14:34 UTC, fabiomorais requested changes

2022-03-10 14:34 UTC, fabiomorais commented on src/data_processing.R
> +              Allocated = sum(InstanceCapacity),
Muda isso Itallo usando aquele csv de tipos de instância. Fica mais bacana

2022-03-10 14:34 UTC, fabiomorais commented on src/main.R
> +                                max_cap = configs$max_cap)
Pq não passa a config para o auto_scaling_algorithm?

2022-03-10 14:34 UTC, fabiomorais commented on src/auto_scaling_algorithm.R
>      new_cores <- reactive_static_policy(system_utilization,
Isso aqui poderia ser uma função compute_scaling que recebe um configuration. A configuration tem referência para a função de autoscaling (reativo, proativo, etc) e as configurações para fazer ela funcionar. Tornaria essa função mais genérica e desacoplada auto_scaling_algorithm

2022-03-14 12:42 UTC, fabiomorais commented on src/main.R
> +readr::write_csv(data_with_auto_scaling, "itallo/output_master_data_api_070222_ds-env291-stable.csv")
Seria melhor deixar paths e file name como parâmetros

2022-03-14 14:32 UTC, fabiomorais commented on src/main.R
> +readr::write_csv(data_with_auto_scaling, "itallo/output_master_data_api_070222_ds-env291-stable.csv")
Ok

2022-04-07 11:06 UTC, kmmelcher requested changes
Acho que as mudanças desse PR ficaram muito boas para o avanço do simulador! está cada vez se tornando mais genérico, parabéns @issilva5 !

2022-04-07 11:06 UTC, kmmelcher commented on src/calculate_adi.R
> +    data[row, "RealADI"] <- real_adi
Qual a diferença entre ADI e RealADI?

2022-04-07 17:06 UTC, issilva5 commented on config.yaml
> +  to_use: "conservative"
concordo.

2022-04-07 17:08 UTC, issilva5 commented on config.yaml
> +    fun: "reactive_static_policy"
É o nome da função que implementa a política e que foi escrita dentro. Ele serve pra permitir reuso de código, a outra opção seria que toda função fosse implementada com o mesmo nome.

2022-04-07 17:08 UTC, issilva5 commented on src/auto_scaling_algorithm.R
> +    }
Esta parte está em processo de mudança, estou estudando mais detalhado sobre como a AWS faz o cooldown.

2022-04-07 17:09 UTC, issilva5 commented on src/calculate_adi.R
> +    data[row, "RealADI"] <- real_adi
É o ADI considerando o dado real, no caso calculado com base utilização real do sistema.

2022-04-07 17:11 UTC, issilva5 commented on src/main.R
> +config_file <- ifelse(is.null(args$config), "config.yaml", args$config)
Não foi isso que eu fiz. É o contrário, o único parâmetro passado agora é o path pro arquivo .yaml com todas as configurações, inclusive o arquivo de entrada. Fazendo assim deixa mais prático a realização de experimentos que variam as configurações, pois você pode criar N arquivos .yaml e chamar iterativamente o simulador variando apenas o path para o arquivo.

2022-04-07 17:16 UTC, issilva5 commented on config.yaml
> +metrics_output_file: "itallo/metrics_master_data_api_240222_ds-env139-stable.csv"
Anonimizei os path

2022-04-11 23:41 UTC, kmmelcher commented on config.yaml
> +    fun: "reactive_static_policy"
Então seria uma abreviação para function? nesse caso acho que func ou funct seria melhor, porque fun é uma abreviação muito curta, eu não consegui identificar e significa outra coisa em inglês

2022-04-12 11:38 UTC, kmmelcher approved these changes

2022-04-12 23:48 UTC, merged